//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesTest.LobbyManagerEmployeesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LobbyManagerEmployeesWS.IEmployeesWS")]
    public interface IEmployeesWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesWS/DeleteCurrentData", ReplyAction="http://tempuri.org/IEmployeesWS/DeleteCurrentDataResponse")]
        string DeleteCurrentData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesWS/CountCurrentData", ReplyAction="http://tempuri.org/IEmployeesWS/CountCurrentDataResponse")]
        string CountCurrentData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesWS/InsertDataSet", ReplyAction="http://tempuri.org/IEmployeesWS/InsertDataSetResponse")]
        string InsertDataSet(System.Data.DataTable data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesWS/InsertDataRow", ReplyAction="http://tempuri.org/IEmployeesWS/InsertDataRowResponse")]
        string InsertDataRow(string id, string name, string lastname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeesWSChannel : EmployeesTest.LobbyManagerEmployeesWS.IEmployeesWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeesWSClient : System.ServiceModel.ClientBase<EmployeesTest.LobbyManagerEmployeesWS.IEmployeesWS>, EmployeesTest.LobbyManagerEmployeesWS.IEmployeesWS {
        
        public EmployeesWSClient() {
        }
        
        public EmployeesWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeesWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DeleteCurrentData() {
            return base.Channel.DeleteCurrentData();
        }
        
        public string CountCurrentData() {
            return base.Channel.CountCurrentData();
        }
        
        public string InsertDataSet(System.Data.DataTable data) {
            return base.Channel.InsertDataSet(data);
        }
        
        public string InsertDataRow(string id, string name, string lastname) {
            return base.Channel.InsertDataRow(id, name, lastname);
        }
    }
}
