//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getProfilePictureOperationCompleted;
    
    private System.Threading.SendOrPostCallback getEmployeesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getEmployeeOperationCompleted;
    
    private System.Threading.SendOrPostCallback getReferredOperationCompleted;
    
    private System.Threading.SendOrPostCallback getEmployeeByWLoginOperationCompleted;
    
    private System.Threading.SendOrPostCallback getCompanyCodeOperationCompleted;
    
    private System.Threading.SendOrPostCallback getEmployeeByWLoginWCompanyOperationCompleted;
    
    private System.Threading.SendOrPostCallback getCostCentersOperationCompleted;
    
    private System.Threading.SendOrPostCallback getDepartmentsOperationCompleted;
    
    /// <remarks/>
    public Service1() {
        this.Url = "http://localhost:61584/Service1.asmx";
    }
    
    /// <remarks/>
    public event getProfilePictureCompletedEventHandler getProfilePictureCompleted;
    
    /// <remarks/>
    public event getEmployeesCompletedEventHandler getEmployeesCompleted;
    
    /// <remarks/>
    public event getEmployeeCompletedEventHandler getEmployeeCompleted;
    
    /// <remarks/>
    public event getReferredCompletedEventHandler getReferredCompleted;
    
    /// <remarks/>
    public event getEmployeeByWLoginCompletedEventHandler getEmployeeByWLoginCompleted;
    
    /// <remarks/>
    public event getCompanyCodeCompletedEventHandler getCompanyCodeCompleted;
    
    /// <remarks/>
    public event getEmployeeByWLoginWCompanyCompletedEventHandler getEmployeeByWLoginWCompanyCompleted;
    
    /// <remarks/>
    public event getCostCentersCompletedEventHandler getCostCentersCompleted;
    
    /// <remarks/>
    public event getDepartmentsCompletedEventHandler getDepartmentsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getProfilePicture", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string getProfilePicture(string svsalid) {
        object[] results = this.Invoke("getProfilePicture", new object[] {
                    svsalid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetProfilePicture(string svsalid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getProfilePicture", new object[] {
                    svsalid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetProfilePicture(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getProfilePictureAsync(string svsalid) {
        this.getProfilePictureAsync(svsalid, null);
    }
    
    /// <remarks/>
    public void getProfilePictureAsync(string svsalid, object userState) {
        if ((this.getProfilePictureOperationCompleted == null)) {
            this.getProfilePictureOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProfilePictureOperationCompleted);
        }
        this.InvokeAsync("getProfilePicture", new object[] {
                    svsalid}, this.getProfilePictureOperationCompleted, userState);
    }
    
    private void OngetProfilePictureOperationCompleted(object arg) {
        if ((this.getProfilePictureCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getProfilePictureCompleted(this, new getProfilePictureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEmployees", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable getEmployees() {
        object[] results = this.Invoke("getEmployees", new object[0]);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetEmployees(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getEmployees", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndgetEmployees(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void getEmployeesAsync() {
        this.getEmployeesAsync(null);
    }
    
    /// <remarks/>
    public void getEmployeesAsync(object userState) {
        if ((this.getEmployeesOperationCompleted == null)) {
            this.getEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeesOperationCompleted);
        }
        this.InvokeAsync("getEmployees", new object[0], this.getEmployeesOperationCompleted, userState);
    }
    
    private void OngetEmployeesOperationCompleted(object arg) {
        if ((this.getEmployeesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getEmployeesCompleted(this, new getEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable getEmployee(string wlogin) {
        object[] results = this.Invoke("getEmployee", new object[] {
                    wlogin});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetEmployee(string wlogin, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getEmployee", new object[] {
                    wlogin}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndgetEmployee(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void getEmployeeAsync(string wlogin) {
        this.getEmployeeAsync(wlogin, null);
    }
    
    /// <remarks/>
    public void getEmployeeAsync(string wlogin, object userState) {
        if ((this.getEmployeeOperationCompleted == null)) {
            this.getEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeeOperationCompleted);
        }
        this.InvokeAsync("getEmployee", new object[] {
                    wlogin}, this.getEmployeeOperationCompleted, userState);
    }
    
    private void OngetEmployeeOperationCompleted(object arg) {
        if ((this.getEmployeeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getEmployeeCompleted(this, new getEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getReferred", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable getReferred() {
        object[] results = this.Invoke("getReferred", new object[0]);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetReferred(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getReferred", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndgetReferred(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void getReferredAsync() {
        this.getReferredAsync(null);
    }
    
    /// <remarks/>
    public void getReferredAsync(object userState) {
        if ((this.getReferredOperationCompleted == null)) {
            this.getReferredOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReferredOperationCompleted);
        }
        this.InvokeAsync("getReferred", new object[0], this.getReferredOperationCompleted, userState);
    }
    
    private void OngetReferredOperationCompleted(object arg) {
        if ((this.getReferredCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getReferredCompleted(this, new getReferredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEmployeeByWLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable getEmployeeByWLogin(string wlogin) {
        object[] results = this.Invoke("getEmployeeByWLogin", new object[] {
                    wlogin});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetEmployeeByWLogin(string wlogin, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getEmployeeByWLogin", new object[] {
                    wlogin}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndgetEmployeeByWLogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void getEmployeeByWLoginAsync(string wlogin) {
        this.getEmployeeByWLoginAsync(wlogin, null);
    }
    
    /// <remarks/>
    public void getEmployeeByWLoginAsync(string wlogin, object userState) {
        if ((this.getEmployeeByWLoginOperationCompleted == null)) {
            this.getEmployeeByWLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeeByWLoginOperationCompleted);
        }
        this.InvokeAsync("getEmployeeByWLogin", new object[] {
                    wlogin}, this.getEmployeeByWLoginOperationCompleted, userState);
    }
    
    private void OngetEmployeeByWLoginOperationCompleted(object arg) {
        if ((this.getEmployeeByWLoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getEmployeeByWLoginCompleted(this, new getEmployeeByWLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCompanyCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable getCompanyCode() {
        object[] results = this.Invoke("getCompanyCode", new object[0]);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCompanyCode(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCompanyCode", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndgetCompanyCode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void getCompanyCodeAsync() {
        this.getCompanyCodeAsync(null);
    }
    
    /// <remarks/>
    public void getCompanyCodeAsync(object userState) {
        if ((this.getCompanyCodeOperationCompleted == null)) {
            this.getCompanyCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCompanyCodeOperationCompleted);
        }
        this.InvokeAsync("getCompanyCode", new object[0], this.getCompanyCodeOperationCompleted, userState);
    }
    
    private void OngetCompanyCodeOperationCompleted(object arg) {
        if ((this.getCompanyCodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCompanyCodeCompleted(this, new getCompanyCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEmployeeByWLoginWCompany", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable getEmployeeByWLoginWCompany(string wlogin) {
        object[] results = this.Invoke("getEmployeeByWLoginWCompany", new object[] {
                    wlogin});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetEmployeeByWLoginWCompany(string wlogin, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getEmployeeByWLoginWCompany", new object[] {
                    wlogin}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndgetEmployeeByWLoginWCompany(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void getEmployeeByWLoginWCompanyAsync(string wlogin) {
        this.getEmployeeByWLoginWCompanyAsync(wlogin, null);
    }
    
    /// <remarks/>
    public void getEmployeeByWLoginWCompanyAsync(string wlogin, object userState) {
        if ((this.getEmployeeByWLoginWCompanyOperationCompleted == null)) {
            this.getEmployeeByWLoginWCompanyOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeeByWLoginWCompanyOperationCompleted);
        }
        this.InvokeAsync("getEmployeeByWLoginWCompany", new object[] {
                    wlogin}, this.getEmployeeByWLoginWCompanyOperationCompleted, userState);
    }
    
    private void OngetEmployeeByWLoginWCompanyOperationCompleted(object arg) {
        if ((this.getEmployeeByWLoginWCompanyCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getEmployeeByWLoginWCompanyCompleted(this, new getEmployeeByWLoginWCompanyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCostCenters", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable getCostCenters() {
        object[] results = this.Invoke("getCostCenters", new object[0]);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCostCenters(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCostCenters", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndgetCostCenters(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void getCostCentersAsync() {
        this.getCostCentersAsync(null);
    }
    
    /// <remarks/>
    public void getCostCentersAsync(object userState) {
        if ((this.getCostCentersOperationCompleted == null)) {
            this.getCostCentersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCostCentersOperationCompleted);
        }
        this.InvokeAsync("getCostCenters", new object[0], this.getCostCentersOperationCompleted, userState);
    }
    
    private void OngetCostCentersOperationCompleted(object arg) {
        if ((this.getCostCentersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCostCentersCompleted(this, new getCostCentersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDepartments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable getDepartments() {
        object[] results = this.Invoke("getDepartments", new object[0]);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetDepartments(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getDepartments", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndgetDepartments(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void getDepartmentsAsync() {
        this.getDepartmentsAsync(null);
    }
    
    /// <remarks/>
    public void getDepartmentsAsync(object userState) {
        if ((this.getDepartmentsOperationCompleted == null)) {
            this.getDepartmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDepartmentsOperationCompleted);
        }
        this.InvokeAsync("getDepartments", new object[0], this.getDepartmentsOperationCompleted, userState);
    }
    
    private void OngetDepartmentsOperationCompleted(object arg) {
        if ((this.getDepartmentsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getDepartmentsCompleted(this, new getDepartmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getProfilePictureCompletedEventHandler(object sender, getProfilePictureCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getProfilePictureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getProfilePictureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getEmployeesCompletedEventHandler(object sender, getEmployeesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getEmployeeCompletedEventHandler(object sender, getEmployeeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getReferredCompletedEventHandler(object sender, getReferredCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getReferredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getReferredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getEmployeeByWLoginCompletedEventHandler(object sender, getEmployeeByWLoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getEmployeeByWLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getEmployeeByWLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getCompanyCodeCompletedEventHandler(object sender, getCompanyCodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCompanyCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCompanyCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getEmployeeByWLoginWCompanyCompletedEventHandler(object sender, getEmployeeByWLoginWCompanyCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getEmployeeByWLoginWCompanyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getEmployeeByWLoginWCompanyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getCostCentersCompletedEventHandler(object sender, getCostCentersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCostCentersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCostCentersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getDepartmentsCompletedEventHandler(object sender, getDepartmentsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getDepartmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getDepartmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}
