//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LobbyManagerService.LobbyManagerWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LobbyManagerWS.IImageCollector")]
    public interface IImageCollector {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageCollector/DoWork", ReplyAction="http://tempuri.org/IImageCollector/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageCollector/DoWork", ReplyAction="http://tempuri.org/IImageCollector/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageCollector/SaveImages", ReplyAction="http://tempuri.org/IImageCollector/SaveImagesResponse")]
        void SaveImages(string desk, string front, string back, string profile, string ocr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageCollector/SaveImages", ReplyAction="http://tempuri.org/IImageCollector/SaveImagesResponse")]
        System.Threading.Tasks.Task SaveImagesAsync(string desk, string front, string back, string profile, string ocr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageCollectorChannel : LobbyManagerService.LobbyManagerWS.IImageCollector, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageCollectorClient : System.ServiceModel.ClientBase<LobbyManagerService.LobbyManagerWS.IImageCollector>, LobbyManagerService.LobbyManagerWS.IImageCollector {
        
        public ImageCollectorClient() {
        }
        
        public ImageCollectorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageCollectorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageCollectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageCollectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public void SaveImages(string desk, string front, string back, string profile, string ocr) {
            base.Channel.SaveImages(desk, front, back, profile, ocr);
        }
        
        public System.Threading.Tasks.Task SaveImagesAsync(string desk, string front, string back, string profile, string ocr) {
            return base.Channel.SaveImagesAsync(desk, front, back, profile, ocr);
        }
    }
}
