//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LobbyManager.EmployeesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeesWS.IEmployeesWebService")]
    public interface IEmployeesWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesWebService/getEmployeesActive", ReplyAction="http://tempuri.org/IEmployeesWebService/getEmployeesActiveResponse")]
        System.Data.DataTable getEmployeesActive();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeesWebServiceChannel : LobbyManager.EmployeesWS.IEmployeesWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeesWebServiceClient : System.ServiceModel.ClientBase<LobbyManager.EmployeesWS.IEmployeesWebService>, LobbyManager.EmployeesWS.IEmployeesWebService {
        
        public EmployeesWebServiceClient() {
        }
        
        public EmployeesWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeesWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getEmployeesActive() {
            return base.Channel.getEmployeesActive();
        }
    }
}
