//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncLobbyManagerEmployees.EmployeesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeesWS.IEmployeesWebService")]
    public interface IEmployeesWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesWebService/SyncEmployees", ReplyAction="http://tempuri.org/IEmployeesWebService/SyncEmployeesResponse")]
        void SyncEmployees();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeesWebServiceChannel : SyncLobbyManagerEmployees.EmployeesWS.IEmployeesWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeesWebServiceClient : System.ServiceModel.ClientBase<SyncLobbyManagerEmployees.EmployeesWS.IEmployeesWebService>, SyncLobbyManagerEmployees.EmployeesWS.IEmployeesWebService {
        
        public EmployeesWebServiceClient() {
        }
        
        public EmployeesWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeesWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SyncEmployees() {
            base.Channel.SyncEmployees();
        }
    }
}
